algoritmo "MediaAluno"
var
   A1, A2 : Caractere
   N1, N2, M: Real

inicio
      Escreva ("Qual o nome do primeiro aluno? ")
      Leia (A1)
      Escreva ("Qual o nome do segundo aluno? ")
      Leia (A2)
      Escreva ("Qual a nota do aluno, ", A1, "?")
      Leia (N1)
      Escreva ("Qual a nota do aluno, ", A2, "?")
      Leia (N2)
      M <- (N1 + N2) /2
      Escreval ("A média entre ", N1, " e ", N2, " é igual á ", M)



fimalgoritmo